"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../globals/Navbar";
import Sidebar from "../globals/Sidebar";
import Footer from "../globals/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism, shadesOfPurple } from "@clerk/themes";
import { useRouter } from "next/navigation";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [dark],
        variables: { colorPrimary: "red" },
        signIn: {
          baseTheme: [dark],
          variables: { colorPrimary: "blue" },
        },
      }}
    >
      <html lang="en">
        <body className={`p-0 m-0 flex`}>
          {(router.pathname === "/login") ||
          (router.pathname === "/signup") ? null : (
            <Sidebar />
          )}

          <div className="w-full">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
